runtime: go111

main: goappsrv

inbound_services:
- warmup

env_variables:

handlers:
- url: /(.*\.js)
  mime_type: text/javascript
  static_files: goappsrv/dist/webapp/\1
  upload: goappsrv/dist/webapp/(.*\.js)

- url: /(.*\.css)
  mime_type: text/css
  static_files: goappsrv/dist/webapp/\1
  upload: goappsrv/dist/webapp/(.*\.css)
  
- url: /(.*\.(ico|eot|svg|ttf|woff|woff2))$
  static_files: goappsrv/dist/webapp/\1
  upload: goappsrv/dist/webapp/.*\.(ico|eot|svg|ttf|woff|woff2)$

- url: /assets/images/(.*\.png)$
  static_files: goappsrv/dist/webapp/assets/images/\1
  upload: goappsrv/dist/webapp/assets/images/(.*\.png)
  
- url: /.*
  script: auto